#!/bin/sh

c() {
	bspc config "$@"
}

c focus_follows_pointer true
c borderless_monocle true
c gapless_monocle true
c single_monocle true
c border_width 0
c window_gap 20

bspc monitor -d {1,11,2,12,3,13,4,14,5,15,6,16,7,17,8,18,9,19,0,10}

for service in wired espanso; do
	systemctl --user start "$service"
done

feh --bg-scale ~/.config/bspwm/desktop.jpg
~/.config/polybar/launch.sh
